import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'SACRED',
			description: 'Scripture Archive of Canonical References, Editions, Digital corpus',
			social: [{ 
				icon: 'github', 
				label: 'GitHub', 
				href: 'https://github.com/withastro/starlight' 
			}],
			customCss: [
				'./src/global.css',
				'./src/fonts.css',
			],
			defaultLocale: 'romn',
			locales: {
				mymr: {
					label: 'မြန်မာ',
					lang: 'my',
				},
				thai: {
					label: 'ไทย',
					lang: 'th',
				},
				sinh: {
					label: 'සිංහල',
					lang: 'si',
				},
				romn: {
					label: 'Roman',
					lang: 'en',
				},
				deva: {
					label: 'देवनागरी',
					lang: 'hi',
				},
				khmr: {
					label: 'ខ្មែរ',
					lang: 'kh',
				},
				laoo: {
					label: 'ລາວ',
					lang: 'lo',
				},
				lana: {
					label: 'ᩃᨶ᩠ᨶ',
					lang: 'ln',
				},
			},
			sidebar: [
                {
                    label: 'Tipiṭaka',
                    collapsed: true,
                    translations: { 
                        'my': 'တိပိဋက',
                        'th': 'ติปิฏก',
                        'si': 'තිපිටක',
                        'en': 'Tipiṭaka',
                        'hi': 'तिपिटक',
                        'kh': 'តិបិដក',
                        'lo': 'ຕິປິຏກ',
                        'ln': 'ᨲᩥᨸᩥᨭᨠ',
                    },
                    items: [
                        { 
                            label: 'Vinayapiṭaka', 
                            collapsed: true,
                            translations: { 
                                'my': 'ဝိနယပိဋက',
                                'th': 'วินัยปิฎก',
                                'si': 'විනයපිටක',
                                'en': 'Vinayapiṭaka',
                                'hi': 'विनयपिटक',
                                'kh': 'វិនយបិដក',
                                'lo': 'ວິນຍປິຏກ',
                                'ln': 'ᩅᩥᨶᩥᨿᨸᩥᨭᨠ',
                            },
                            items: [
                                { 
                                    label: 'Pārājikapāḷi',
                                    collapsed: true,
                                    translations: { 
                                        'my': 'ပါရာဇိကပါဠိ', 
                                        'th': 'ปาราชิกปาฬิ',
                                        'si': 'පාරාජිකපාළි',
                                        'en': 'Pārājikapāḷi',
                                        'hi': 'पाराजिकपाळि',
                                        'kh': 'បារាជិកបាឡិ',
                                        'lo': 'ປາຣາຊິກປາຬິ',
                                        'ln': 'ᨸᩣᩁᩣᨧᩥᨠᩣᨶᩣᩊᩥ',
                                    },
                                    items: [
                                        {
                                            label: 'Mahāvibhaṅga',
                                            collapsed: true,
                                            translations: { 
                                                'my': 'မဟာဝိဘင်္ဂ', 
                                                'th': 'มหาวิภงฺค',
                                                'si': 'මහාවිභඞ්ග',
                                                'en': 'Mahāvibhaṅga',
                                                'hi': 'महाविभङ्ग',
                                                'kh': 'មហាវិភង្គ',
                                                'lo': 'ມຫາວິຠງ຺ຄ',
                                                'ln': 'ᨾᩉᩣᩅᩥᨽᨦ᩠ᨣ',
                                            },
                                            autogenerate: { directory: 'mula/vi/paraj' } 
                                        }
                                    ],
                                },
                                { 
                                    label: 'Pācittiyapāḷi',
                                    collapsed: true,
                                    translations: { 
                                        'my': 'ပါစိတ္တိယပါဠိ', 
                                        'th': 'ปาจิตฺติยปาฬิ',
                                        'si': 'පාචිත්තියපාළි',
                                        'en': 'Pācittiyapāḷi',
                                        'hi': 'पाचित्तियपाळि',
                                        'kh': 'បាចិត្តិយបាឡិ',
                                        'lo': 'ປາຈິຕ຺ຕິຍປາຬິ',
                                        'ln': 'ᨸᩣᨧᩥᨲ᩠ᨲᩥᨿᨸᩣᩊᩥ',
                                    },
                                    items: [
                                        {
                                            label: 'Mahāvibhaṅga',
                                            collapsed: true,
                                            translations: { 
                                                'my': 'မဟာဝိဘင်္ဂ', 
                                                'th': 'มหาวิภงฺค',
                                                'si': 'මහාවිභඞ්ග',
                                                'en': 'Mahāvibhaṅga',
                                                'hi': 'महाविभङ्ग',
                                                'kh': 'មហាវិភង្គ',
                                                'lo': 'ມຫາວິຠງ຺ຄ',
                                                'ln': 'ᨾᩉᩣᩅᩥᨽᨦ᩠ᨣ',
                                            },
                                            items: [
                                                {
                                                    label: 'Pācittiyakaṇḍa',
                                                    translations: {
                                                        'my': 'ပါစိတ္တိယကဏ္ဍ', 
                                                        'th': 'ปาจิตฺติยกณฺฑ',
                                                        'si': 'පාචිත්තියකණ්ඩ',
                                                        'en': 'pācittiyakaṇḍa',
                                                        'hi': 'पाचित्तियकण्ड',
                                                        'kh': 'បាចិត្តិយកណ្ឌ',
                                                        'lo': 'ປາຈິຕ຺ຕິຍກຓ຺ຑ',
                                                        'ln': 'ᨸᩣᨧᩥᨲ᩠ᨲᩥᨿᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/1.md',
                                                },
                                                {
                                                    label: 'Pāṭidesanīyakaṇḍa',
                                                    translations: {
                                                        'my': 'ပါဋိဒေသနီယကဏ္ဍ', 
                                                        'th': 'ปาฏิเทสนียกณฺฑ',
                                                        'si': 'පාටිදේසනීයකණ්ඩ',
                                                        'en': 'pāṭidesanīyakaṇḍa',
                                                        'hi': 'पाटिदेसनीयकण्ड',
                                                        'kh': 'បាដិទេសនីយកណ្ឌ',
                                                        'lo': 'ປາຏິເທສນີຍກຓ຺ຑ',
                                                        'ln': 'ᨸᩣᨭᩥᨯᩮᩈᨶᩦᨿᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/2.md',
                                                },                                                
                                                {
                                                    label: 'Sekhiyakaṇḍa',
                                                    translations: {
                                                        'my': 'သေခိယကဏ္ဍ', 
                                                        'th': 'เสขิยกณฺฑ',
                                                        'si': 'සේඛියකණ්ඩ',
                                                        'en': 'sekhiyakaṇḍa',
                                                        'hi': 'सेखियकण्ड',
                                                        'kh': 'សេខិយកណ្ឌ',
                                                        'lo': 'ເສຂິຍກຓ຺ຑ',
                                                        'ln': 'ᩈᩮᨡᩥᨿᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/3.md',
                                                },                                                
                                                {
                                                    label: 'Adhikaraṇasamatha',
                                                    translations: {
                                                        'my': 'အဓိကရဏသမထ', 
                                                        'th': 'อธิกรณสมถ',
                                                        'si': 'අධිකරණසමථ',
                                                        'en': 'adhikaraṇasamatha',
                                                        'hi': 'अधिकरणसमथ',
                                                        'kh': 'អធិករណសមថ',
                                                        'lo': 'ອທິກຣຓສມຖ',
                                                        'ln': 'ᩋᨯᩥᨠᩁᨱᩈᨾᨳ',
                                                    },
                                                    link: '/mula/vi/pacit/4.md',
                                                },                                                
                                            ]
                                        },
                                        {
                                            label: 'Bhikkhunivibhaṅga',
                                            collapsed: true,
                                            translations: { 
                                                'my': 'ဘိက္ခုနိဝိဘင်္ဂ', 
                                                'th': 'ภิกฺขุนิวิภงฺค',
                                                'si': 'භික්ඛුනිවිභඞ්ග',
                                                'en': 'bhikkhunivibhaṅga',
                                                'hi': 'भिक्खुनिविभङ्ग',
                                                'kh': 'ភិក្ខុនិវិភង្គ',
                                                'lo': 'ຠິກ຺ຂຸນິວິຠງ຺ຄ',
                                                'ln': 'ᨽᩥᨠ᩠ᨡᩩᨶᩥᩅᩥᨽᨦ᩠ᨣ',
                                            },
                                            items: [
                                                {
                                                    label: 'Pārājikakaṇḍa',
                                                    translations: {
                                                        'my': 'ပါရာဇိကကဏ္ဍ',
                                                        'th': 'ปาราชิกกณฺฑ',
                                                        'si': 'පාරාජිකකණ්ඩ',
                                                        'en': 'Pārājikakaṇḍa',
                                                        'hi': 'पाराजिककण्ड',
                                                        'kh': 'បារាជិកកណ្ឌ ',
                                                        'lo': 'ປາຣາຊິກກຓ຺ຑ',
                                                        'ln': 'ᨸᩣᩁᩣᨧᩥᨠᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/5.md',
                                                },
                                                {
                                                    label: 'Saṃghādisesakaṇḍa',
                                                    translations: {
                                                        'my': 'သံဃာဒိသေသကဏ္ဍ',
                                                        'th': 'สํฆาทิเสสกณฺฑ',
                                                        'si': 'සංඝාදිසෙසකණ්ඩ',
                                                        'en': 'saṃghādisesakaṇḍa',
                                                        'hi': 'संघादिसेसकण्ड',
                                                        'kh': 'សំឃាទិសេសកណ្ឌ',
                                                        'lo': 'ສໍຄາທິເສສກຓ຺ຑ',
                                                        'ln': 'ᩈᩴᨣᩣᨯᩥᩈᩮᩈᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/6.md',
                                                },
                                                {
                                                    label: 'Nissaggiyakaṇḍa',
                                                    translations: {
                                                        'my': 'နိဿဂ္ဂိယကဏ္ဍ',
                                                        'th': 'นิสฺสคฺคิยกณฺฑ',
                                                        'si': 'නිස්සග්ගියකණ්ඩ',
                                                        'en': 'nissaggiyakaṇḍa',
                                                        'hi': 'निस्सग्गियकण्ड',
                                                        'kh': 'និស្សគ្គិយកណ្ឌ',
                                                        'lo': 'ນິສ຺ສຄ຺ຄິຍກຓ຺ຑ',
                                                        'ln': 'ᨶᩥᩈ᩠ᩈᨣ᩠ᨣᩥᨿᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/7.md',
                                                },
                                                {
                                                    label: 'Pācittiyakaṇḍa',
                                                    translations: {
                                                        'my': 'ပါစိတ္တိယကဏ္ဍ',
                                                        'th': 'ปาจิตฺติยกณฺฑ',
                                                        'si': 'පාචිත්තියකණ්ඩ',
                                                        'en': 'pācittiyakaṇḍa',
                                                        'hi': 'पाचित्तियकण्ड',
                                                        'kh': 'បាចិត្តិយកណ្ឌ',
                                                        'lo': 'ປາຈິຕ຺ຕິຍກຓ຺ຑ',
                                                        'ln': 'ᨸᩣᨧᩥᨲ᩠ᨲᩥᨿᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/8.md',
                                                },
                                                {
                                                    label: 'Pāṭidesanīyakaṇḍa',
                                                    translations: {
                                                        'my': 'ပါဋိဒေသနီယကဏ္ဍ',
                                                        'th': 'ปาฏิเทสนียกณฺฑ',
                                                        'si': 'පාටිදේසනීයකණ්ඩ',
                                                        'en': 'pāṭidesanīyakaṇḍa',
                                                        'hi': 'पाटिदेसनीयकण्ड',
                                                        'kh': 'បាដិទេសនីយកណ្ឌ',
                                                        'lo': 'ປາຏິເທສນີຍກຓ຺ຑ',
                                                        'ln': 'ᨸᩣᨭᩥᨯᩮᩈᨶᩦᨿᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/9.md',
                                                },
                                                {
                                                    label: 'Sekhiyakaṇḍa',
                                                    translations: {
                                                        'my': 'သေခိယကဏ္ဍ',
                                                        'th': 'เสขิยกณฺฑ',
                                                        'si': 'සේඛියකණ්ඩ',
                                                        'en': 'sekhiyakaṇḍa',
                                                        'hi': 'सेखियकण्ड',
                                                        'kh': 'សេខិយកណ្ឌ',
                                                        'lo': 'ເສຂິຍກຓ຺ຑ',
                                                        'ln': 'ᩈᩮᨡᩥᨿᨠᨱ᩠ᨯ',
                                                    },
                                                    link: '/mula/vi/pacit/10.md',
                                                },
                                                {
                                                    label: 'Adhikaraṇasamatha',
                                                    translations: {
                                                        'my': 'အဓိကရဏသမထ',
                                                        'th': 'อธิกรณสมถ',
                                                        'si': 'අධිකරණසමථ',
                                                        'en': 'adhikaraṇasamatha',
                                                        'hi': 'अधिकरणसमथ',
                                                        'kh': 'អធិករណសមថ',
                                                        'lo': 'ອທິກຣຓສມຖ',
                                                        'ln': 'ᩋᨯᩥᨠᩁᨱᩈᨾᨳ',
                                                    },
                                                    link: '/mula/vi/pacit/11.md',
                                                },
                                            ]
                                        }
                                    ],
                                },
                                {
                                    label: 'Mahāvaggapāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'မဟာဝဂ္ဂပါဠိ',
                                        'th': 'มหาวคฺคปาฬิ',
                                        'si': 'මහාවග්ගපාළි',
                                        'en': 'Mahāvaggapāḷi',
                                        'hi': 'महावग्गपाळि',
                                        'kh': 'មហាវគ្គបាឡិ',
                                        'lo': 'ມຫາວຄ຺ຄປາຬິ',
                                        'ln': 'ᨾᩉᩣᩅᨣ᩠ᨣᨸᩣᩊᩥ',
                                    },
                                    autogenerate: {directory: 'mula/vi/maha-vi'}
                                },
                                {
                                    label: 'Cūḷavaggapāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'စူဠဝဂ္ဂပါဠိ',
                                        'th': 'จูฬวคฺคปาฬิ',
                                        'si': 'චූළවග්ගපාළි',
                                        'en': 'Cūḷavaggapāḷi',
                                        'hi': 'चूळवग्गपाळि',
                                        'kh': 'ចូឡវគ្គបាឡិ',
                                        'lo': 'ຈູຬວຄ຺ຄປາຬິ',
                                        'ln': 'ᨧᩪᩊᩅᨣ᩠ᨣᨸᩣᩊᩥ',
                                    },
                                    autogenerate: {directory: 'mula/vi/cula-vi'}
                                },
                                {
                                    label: 'Parivārapāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ပရိဝါရပါဠိ',
                                        'th': 'ปริวารปาฬิ',
                                        'si': 'පරිවාරපාළි',
                                        'en': 'Parivārapāḷi',
                                        'hi': 'परिवारपाळि',
                                        'kh': 'បរិវារបាឡិ',
                                        'lo': 'ປຣິວາຣປາຬິ',
                                        'ln': 'ᨸᩁᩥᩅᩣᩁᨸᩣᩊᩥ',
                                    },
                                    autogenerate: {directory: 'mula/vi/pariv'}
                                }
                            ]
                        },
                        {
                            label: 'Suttantapiṭaka',
                            collapsed: true,
                            translations: { 
                                'my': 'သုတ္တန္တပိဋက',
                                'th': 'สุตฺตนฺตปิฏก',
                                'si': 'සුත්තන්තපිටක',
                                'en': 'Suttantapiṭaka',
                                'hi': 'सुत्तन्तपिटक',
                                'kh': 'សុត្តន្តបិដក',
                                'lo': 'ສຸຕ຺ຕນ຺ຕປິຏກ',
                                'ln': 'ᩈᩩᨲ᩠ᨲᨶ᩠ᨲᨸᩥᨭᨠ',
                            },
                            items: [
                                { 
                                    label: 'Dīghanikāya',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ဒီဃနိကာယ',
                                        'th': 'ทีฆนิกาย',
                                        'si': 'දීඝනිකාය',
                                        'en': 'Dīghanikāya',
                                        'hi': 'दीघनिकाय',
                                        'kh': 'ទីឃនិកាយ',
                                        'lo': 'ທີຄນິກາຍ',
                                        'ln': 'ᨴᩦᨥᨶᩥᨠᩣᨿ',
                                    },
                                    items: [
                                        { 
                                            label: 'Sīlakkhandhavaggapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'သီလက္ခန္ဓဝဂ္ဂပါဠိ',
                                                'th': 'สีลกฺขนฺธวคฺคปาฬิ',
                                                'si': 'සීලක්ඛන්ධවග්ගපාළි',
                                                'en': 'Sīlakkhandhavaggapāḷi',
                                                'hi': 'सीलक्खन्धवग्गपाळि',
                                                'kh': 'សីលក្ខន្ធវគ្គបាឡិ',
                                                'lo': 'ສີລກ຺ຂນ຺ຘວຄ຺ຄປາຬິ',
                                                'ln': 'ᩈᩦᩃᨠ᩠ᨡᨶ᩠ᨵᩅᨣ᩠ᨣᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/di/sila'}
                                        },
                                        { 
                                            label: 'Mahāvaggapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'မဟာဝဂ္ဂပါဠိ',
                                                'th': 'มหาวคฺคปาฬิ',
                                                'si': 'මහාවග්ගපාළි',
                                                'en': 'Mahāvaggapāḷi',
                                                'hi': 'महावग्गपाळि',
                                                'kh': 'មហាវគ្គបាឡិ',
                                                'lo': 'ມຫາວຄ຺ຄປາຬິ',
                                                'ln': 'ᨾᩉᩣᩅᨣ᩠ᨣᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/di/maha-di'}
                                        },
                                        { 
                                            label: 'Pāthikavaggapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပါထိကဝဂ္ဂပါဠိ',
                                                'th': 'ปาถิกวคฺคปาฬิ',
                                                'si': 'පාථිකවග්ගපාළි',
                                                'en': 'Pāthikavaggapāḷi',
                                                'hi': 'पाथिकवग्गपाळि',
                                                'kh': 'បាថិកវគ្គបាឡិ',
                                                'lo': 'ປາຖິກວຄ຺ຄປາຬິ',
                                                'ln': 'ᨸᩣᨳᩥᨠᩅᨣ᩠ᨣᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/di/pathika'}
                                        },
                                    ]
                                },
                                { 
                                    label: 'Majjhimanikāya',
                                    collapsed: true,
                                    translations: {
                                        'my': 'မဇ္ဈိမနိကာယ',
                                        'th': 'มชฺฌิมนิกาย',
                                        'si': 'මජ්ඣිමනිකාය',
                                        'en': 'Majjhimanikāya',
                                        'hi': 'मज्झिमनिकाय',
                                        'kh': 'មជ្ឈិមនិកាយ',
                                        'lo': 'ມຊ຺ຌິມນິກາຍ',
                                        'ln': 'မဇ္ဈိမနိကာယ',
                                    },
                                    items: [
                                        {
                                            label: 'Mūlapaṇṇāsapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'မူလပဏ္ဏာသပါဠိ',
                                                'th': 'มูลปณฺณาสปาฬิ',
                                                'si': 'මූලපණ්ණාසපාළි',
                                                'en': 'Mūlapaṇṇāsapāḷi',
                                                'hi': 'मूलपण्णासपाळि',
                                                'kh': 'មូលបណ្ណាសបាឡិ',
                                                'lo': 'ມູລປຓ຺ຓາສປາຬິ',
                                                'ln': 'ᨾᩪᩃᨸᨱ᩠ᨱᩣᩈᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ma/mula'}
                                        },
                                        {
                                            label: 'Majjhimapaṇṇāsapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'မဇ္ဈိမပဏ္ဏာသပါဠိ',
                                                'th': 'มชฺฌิมปณฺณาสปาฬิ',
                                                'si': 'මජ්ඣිමපණ්ණාසපාළි',
                                                'en': 'Majjhimapaṇṇāsapāḷi',
                                                'hi': 'मज्झिमपण्णासपाळि',
                                                'kh': 'មជ្ឈិមបណ្ណាសបាឡិ',
                                                'lo': 'ມຊ຺ຌິມປຓ຺ຓາສປາຬິ',
                                                'ln': 'ᨾᨩ᩠ᨫᩥᨾᨸᨱ᩠ᨱᩣᩈᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ma/majjh'}
                                        },
                                        {
                                            label: 'Uparipaṇṇāsapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဥပရိပဏ္ဏာသပါဠိ',
                                                'th': 'อุปริปณฺณาสปาฬิ',
                                                'si': 'උපරිපණ්ණාසපාළි',
                                                'en': 'Uparipaṇṇāsapāḷi',
                                                'hi': 'उपरिपण्णासपाळि',
                                                'kh': 'ឧបរិបណ្ណាសបាឡិ',
                                                'lo': 'ອຸປຣິປຓ຺ຓາສປາຬິ',
                                                'ln': 'ᩏᨸᩁᩥᨸᨱ᩠ᨱᩣᩈᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ma/upari'}
                                        },
                                    ]
                                },
                                { 
                                    label: 'Saṃyuttanikāya',
                                    collapsed: true,
                                    translations: {
                                        'my': 'သံယုတ္တနိကာယ',
                                        'th': 'สํยุตฺตนิกาย',
                                        'si': 'සංයුත්තනිකාය',
                                        'en': 'Saṃyuttanikāya',
                                        'hi': 'संयुत्तनिकाय',
                                        'kh': 'សំយុត្តនិកាយ',
                                        'lo': 'ສໍຍຸຕ຺ຕນິກາຍ',
                                        'ln': 'ᩈᩴᨿᩩᨲ᩠ᨲᨶᩥᨠᩣᨿ',
                                    },
                                    items: [
                                        {
                                            label: 'Sagāthāvaggasaṃyuttapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'သဂါထာဝဂ္ဂသံယုတ္တပါဠိ',
                                                'th': 'สคาถาวคฺคสํยุตฺตปาฬิ',
                                                'si': 'සගාථාවග්ගසංයුත්තපාළි',
                                                'en': 'Sagāthāvaggasaṃyuttapāḷi',
                                                'hi': 'सगाथावग्गसंयुत्तपाळि',
                                                'kh': 'សគាថាវគ្គសំយុត្តបាឡិ',
                                                'lo': 'ສຄາຖາວຄ຺ຄສໍຍຸຕ຺ຕປາຬິ',
                                                'ln': 'ᩈᨣᩣᨳᩣᩅᨣ᩠ᨣᩈᩴᨿᩩᨲ᩠ᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/sa/saga'}
                                        },
                                        {
                                            label: 'Nidānavaggasaṃyuttapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'နိဒါနဝဂ္ဂသံယုတ္တပါဠိ',
                                                'th': 'นิทานวคฺคสํยุตฺตปาฬิ',
                                                'si': 'නිදානවග්ගසංයුත්තපාළි',
                                                'en': 'Nidānavaggasaṃyuttapāḷi',
                                                'hi': 'निदानवग्गसंयुत्तपाळि',
                                                'kh': 'និទានវគ្គសំយុត្តបាឡិ',
                                                'lo': 'ນິທານວຄ຺ຄສໍຍຸຕ຺ຕປາຬິ',
                                                'ln': 'ᨶᩥᨴᩣᨶᩅᨣ᩠ᨣᩈᩴᨿᩩᨲ᩠ᨲᨸᩣᩊᩥ',
                                            },                                            
                                            autogenerate: {directory: 'mula/su/sa/nidana'},
                                        },
                                        {
                                            label: 'Khandhavaggasaṃyuttapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ခန္ဓဝဂ္ဂသံယုတ္တပါဠိ',
                                                'th': 'ขนฺธวคฺคสํยุตฺตปาฬิ',
                                                'si': 'ඛන්ධවග්ගසංයුත්තපාළි',
                                                'en': 'Khandhavaggasaṃyuttapāḷi',
                                                'hi': 'खन्धवग्गसंयुत्तपाळि',
                                                'kh': 'ខន្ធវគ្គសំយុត្តបាឡិ',
                                                'lo': 'ຂນ຺ຘວຄ຺ຄສໍຍຸຕ຺ຕປາຬິ',
                                                'ln': 'ᨡᨶ᩠ᨵᩅᨣ᩠ᨣᩈᩴᨿᩩᨲ᩠ᨲᨸᩣᩊᩥ',
                                            },                                            
                                            autogenerate: {directory: 'mula/su/sa/khandha'},
                                        },
                                        {
                                            label: 'Saḷāyatanavaggasaṃyuttapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'သဠာယတနဝဂ္ဂသံယုတ္တပါဠိ',
                                                'th': 'สฬายตนวคฺคสํยุตฺตปาฬิ',
                                                'si': 'සළායතනවග්ගසංයුත්තපාළි',
                                                'en': 'Saḷāyatanavaggasaṃyuttapāḷi',
                                                'hi': 'सळायतनवग्गसंयुत्तपाळि',
                                                'kh': 'សឡាយតនវគ្គសំយុត្តបាឡិ',
                                                'lo': 'ສຬາຍຕນວຄ຺ຄສໍຍຸຕ຺ຕປາຬິ',
                                                'ln': 'ᩈᩊᩣᨶᩦᨶᩅᨣ᩠ᨣᩈᩴᨿᩩᨲ᩠ᨲᨸᩣᩊᩥ',
                                            },                                            
                                            autogenerate: {directory: 'mula/su/sa/salaya'},
                                        },
                                        {
                                            label: 'Mahāvaggasaṃyuttapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'မဟာဝဂ္ဂသံယုတ္တပါဠိ',
                                                'th': 'มหาวคฺคสํยุตฺตปาฬิ',
                                                'si': 'මහාවග්ගසංයුත්තපාළි',
                                                'en': 'Mahāvaggasaṃyuttapāḷi',
                                                'hi': 'महावग्गसंयुत्तपाळि',
                                                'kh': 'មហាវគ្គសំយុត្តបាឡិ',
                                                'lo': 'ມຫາວຄ຺ຄສໍຍຸຕ຺ຕປາຬິ',
                                                'ln': 'ᨾᩉᩣᩅᨣ᩠ᨣᩈᩴᨿᩩᨲ᩠ᨲᨸᩣᩊᩥ',
                                            },                                            
                                            autogenerate: {directory: 'mula/su/sa/maha-sa'},
                                        },
                                    ]
                                },
                                { 
                                    label: 'Aṅguttaranikāya',
                                    collapsed: true,
                                    translations: {
                                        'my': 'အင်္ဂုတ္တရနိကာယ',
                                        'th': 'องฺคุตฺตรนิกาย',
                                        'si': 'අඞ්ගුත්තරනිකාය',
                                        'en': 'Aṅguttaranikāya',
                                        'hi': 'अङ्गुत्तरनिकाय',
                                        'kh': 'អង្គុត្តរនិកាយ',
                                        'lo': 'ອງ຺ຄຸຕ຺ຕຣນິກາຍ',
                                        'ln': 'ᩋᨦ᩠ᨣᩩᨲ᩠ᨲᩁᨶᩥᨠᩣᨿ',
                                    },
                                    items: [
                                        { 
                                            label: 'Ekakanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဧကကနိပါတပါဠိ',
                                                'th': 'เอกกนิปาตปาฬิ',
                                                'si': 'එකකනිපාතපාළි',
                                                'en': 'Ekakanipātapāḷi',
                                                'hi': 'एककनिपातपाळि',
                                                'kh': 'ឯកកនិបាតបាឡិ',
                                                'lo': 'ເອກກນິປາຕປາຬິ',
                                                'ln': 'ᩑᨠᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/eka'},
                                        },
                                        { 
                                            label: 'Dukanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဒုကနိပါတပါဠိ',
                                                'th': 'ทุกนิปาตปาฬิ',
                                                'si': 'දුකනිපාතපාළි',
                                                'en': 'Dukanipātapāḷi',
                                                'hi': 'दुकनिपातपाळि',
                                                'kh': 'ទុកនិបាតបាឡិ',
                                                'lo': 'ທຸກນິປາຕປາຬິ',
                                                'ln': 'ᨴᩩᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/duka'},
                                        },
                                        { 
                                            label: 'Tikanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'တိကနိပါတပါဠိ',
                                                'th': 'ติกนิปาตปาฬิ',
                                                'si': 'තිකනිපාතපාළි',
                                                'en': 'Tikanipātapāḷi',
                                                'hi': 'तिकनिपातपाळि',
                                                'kh': 'តិកនិបាតបាឡិ',
                                                'lo': 'ຕິກນິປາຕປາຬິ',
                                                'ln': 'ᨲᩥᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/tika'},
                                        },
                                        { 
                                            label: 'Catukkanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'စတုက္ကနိပါတပါဠိ',
                                                'th': 'จตุกฺกนิปาตปาฬิ',
                                                'si': 'චතුක්කනිපාතපාළි',
                                                'en': 'Catukkanipātapāḷi',
                                                'hi': 'चतुक्कनिपातपाळि',
                                                'kh': 'ចតុក្កនិបាតបាឡិ',
                                                'lo': 'ຈຕຸກ຺ກນິປາຕປາຬິ',
                                                'ln': 'ᨧᨲᩩᨠ᩠ᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/catukka'},
                                        },
                                        { 
                                            label: 'Pañcakanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပဉ္စကနိပါတပါဠိ',
                                                'th': 'ปญฺจกนิปาตปาฬิ',
                                                'si': 'පඤ්චකනිපාතපාළි',
                                                'en': 'Pañcakanipātapāḷi',
                                                'hi': 'पञ्चकनिपातपाळि',
                                                'kh': 'បញ្ចកនិបាតបាឡិ',
                                                'lo': 'ປຎ຺ຈກນິປາຕປາຬິ',
                                                'ln': 'ᨸᨬ᩠ᨧᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/panca'},
                                        },
                                        { 
                                            label: 'Chakkanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဆက္ကနိပါတပါဠိ',
                                                'th': 'ฉกฺกนิปาตปาฬิ',
                                                'si': 'ඡක්කනිපාතපාළි',
                                                'en': 'Chakkanipātapāḷi',
                                                'hi': 'छक्कनिपातपाळि',
                                                'kh': 'ឆក្កនិបាតបាឡិ',
                                                'lo': 'ຉກ຺ກນິປາຕປາຬິ',
                                                'ln': 'ᨨᨠ᩠ᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/chakka'},
                                        },
                                        { 
                                            label: 'Sattakanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'သတ္တကနိပါတပါဠိ',
                                                'th': 'สตฺตกนิปาตปาฬิ',
                                                'si': 'සත්තකනිපාතපාළි',
                                                'en': 'Sattakanipātapāḷi',
                                                'hi': 'सत्तकनिपातपाळि',
                                                'kh': 'សត្តកនិបាតបាឡិ',
                                                'lo': 'ສຕ຺ຕກນິປາຕປາຬິ',
                                                'ln': 'ᩈᨲ᩠ᨲᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/sattaka'},
                                        },
                                        { 
                                            label: 'Aṭṭhakanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'အဋ္ဌကနိပါတပါဠိ',
                                                'th': 'อฏฺฐกนิปาตปาฬิ',
                                                'si': 'අට්ඨකනිපාතපාළි',
                                                'en': 'Aṭṭhakanipātapāḷi',
                                                'hi': 'अट्ठकनिपातपाळि',
                                                'kh': 'អដ្ឋកនិបាតបាឡិ',
                                                'lo': 'ອຏ຺ຕກນິປາຕປາຬິ',
                                                'ln': 'ᩋᨭ᩠ᨮᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/atthaka'},
                                        },
                                        { 
                                            label: 'Navakanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'နဝကနိပါတပါဠိ',
                                                'th': 'นวกนิปาตปาฬิ',
                                                'si': 'නවකනිපාතපාළි',
                                                'en': 'Navakanipātapāḷi',
                                                'hi': 'नवकनिपातपाळि',
                                                'kh': 'នវកនិបាតបាឡិ',
                                                'lo': 'ນວກນິປາຕປາຬິ',
                                                'ln': 'ᨶᩅᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/navaka'},
                                        },
                                        { 
                                            label: 'Dasakanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဒသကနိပါတပါဠိ',
                                                'th': 'ทสกนิปาตปาฬิ',
                                                'si': 'දසකනිපාතපාළි',
                                                'en': 'Dasakanipātapāḷi',
                                                'hi': 'दसकनिपातपाळि',
                                                'kh': 'ទសកនិបាតបាឡិ',
                                                'lo': 'ທສກນິປາຕປາຬິ',
                                                'ln': 'ᨴᩈᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/dasaka'},
                                        },
                                        { 
                                            label: 'Ekādasakanipātapāḷi',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဧကာဒသကနိပါတပါဠိ',
                                                'th': 'เอกาทสกนิปาตปาฬิ',
                                                'si': 'එකාදසකනිපාතපාළි',
                                                'en': 'Ekādasakanipātapāḷi',
                                                'hi': 'एकादसकनिपातपाळि',
                                                'kh': 'ឯកាទសកនិបាតបាឡិ',
                                                'lo': 'ເອກາທສກນິປາຕປາຬິ',
                                                'ln': 'ᩑᨠᩣᨴᩈᨠᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/an/ekadasaka'},
                                        },                                        
                                    ]
                                },
                                { 
                                    label: 'Khuddakanikāya',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ခုဒ္ဒကနိကာယ',
                                        'th': 'ขุทฺทกนิกาย',
                                        'si': 'ඛුද්දකනිකාය',
                                        'en': 'Khuddakanikāya',
                                        'hi': 'खुद्दकनिकाय',
                                        'kh': 'ខុទ្ទកនិកាយ',
                                        'lo': 'ຂຸທ຺ທກນິກາຍ',
                                        'ln': 'ᨡᩩᨴ᩠ᨴᩣᨶᩥᩣᨿ',
                                    },
                                    items: [
                                        {
                                            label: 'Khuddakapāṭhapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ခုဒ္ဒကပါဌပါဠိ',
                                                'th': 'ขุทฺทกปาฐปาฬิ',
                                                'si': 'ඛුද්දකපාඨපාළි',
                                                'en': 'Khuddakapāṭhapāḷi',
                                                'hi': 'खुद्दकपाठपाळि',
                                                'kh': 'ខុទ្ទកបាឋបាឡិ',
                                                'lo': 'ຂຸທ຺ທກປາຐປາຬິ',
                                                'ln': 'ᨡᩩᨴ᩠ᨴᨠᨸᩣᨮᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/khp'}
                                        },
                                        {
                                            label: 'Dhammapadapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဓမ္မပဒပါဠိ',
                                                'th': 'ธมฺมปทปาฬิ',
                                                'si': 'ධම්මපදපාළි',
                                                'en': 'Dhammapadapāḷi',
                                                'hi': 'धम्मपदपाळि',
                                                'kh': 'ធម្មបទបាឡិ',
                                                'lo': 'ຘມ຺ມປທປາຬິ',
                                                'ln': 'ᨵᨾ᩠ᨾᨸᨴᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/dhp'}
                                        },
                                        {
                                            label: 'Udānapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဥဒါနပါဠိ',
                                                'th': 'อุทานปาฬิ',
                                                'si': 'උදානපාළි',
                                                'en': 'Udānapāḷi',
                                                'hi': 'उदानपाळि',
                                                'kh': 'ឧទានបាឡិ',
                                                'lo': 'ອຸທານປາຬິ',
                                                'ln': 'ᩏᨴᩣᨶᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/ud'}
                                        },
                                        {
                                            label: 'Itivuttakapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဣတိဝုတ္တကပါဠိ',
                                                'th': 'อิติวุตฺตกปาฬิ',
                                                'si': 'ඉතිවුත්තකපාළි',
                                                'en': 'Itivuttakapāḷi',
                                                'hi': 'इतिवुत्तकपाळि',
                                                'kh': 'ឥតិវុត្តកបាឡិ',
                                                'lo': 'ອິຕິວຸຕ຺ຕກປາຬິ',
                                                'ln': 'ᩍᨲᩥᩅᩩᨲ᩠ᨲᨠᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/iti'}
                                        },
                                        {
                                            label: 'Suttanipātapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'သုတ္တနိပါတပါဠိ',
                                                'th': 'สุตฺตนิปาตปาฬิ',
                                                'si': 'සුත්තනිපාතපාළි',
                                                'en': 'Suttanipātapāḷi',
                                                'hi': 'सुत्तनिपातपाळि',
                                                'kh': 'សុត្តនិបាតបាឡិ',
                                                'lo': 'ສຸຕ຺ຕນິປາຕປາຬິ',
                                                'ln': 'ᩈᩩᨲ᩠ᨲᨶᩥᨸᩣᨲᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/snp'}
                                        },
                                        {
                                            label: 'Vimānavatthupāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဝိမာနဝတ္ထုပါဠိ',
                                                'th': 'วิมานวตฺถุปาฬิ',
                                                'si': 'විමානවත්ථුපාළි',
                                                'en': 'Vimānavatthupāḷi',
                                                'hi': 'विमानवत्थुपाळि',
                                                'kh': 'វិមានវត្ថុបាឡិ',
                                                'lo': 'ວິມານວຕ຺ຖຸປາຬິ',
                                                'ln': 'ᩅᩥᨾᩣᨶᩅᨲ᩠ᨳᩩᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/vv'}
                                        },
                                        {
                                            label: 'Petavatthupāḷi',
                                            collapsed: true, 
                                            translations: {
                                                'my': 'ပေတဝတ္ထုပါဠိ',
                                                'th': 'เปตวตฺถุปาฬิ',
                                                'si': 'පෙතවත්ථුපාළි',
                                                'en': 'Petavatthupāḷi',
                                                'hi': 'पेतवत्थुपाळि',
                                                'kh': 'បេតវត្ថុបាឡិ',
                                                'lo': 'ເປຕວຕ຺ຖຸປາຬິ',
                                                'ln': 'ᨸᩮᨲᩅᨲ᩠ᨳᩩᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/petav'}
                                        },
                                        {
                                            label: 'Theragāthāpāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ထေရဂါထာပါဠိ',
                                                'th': 'เถรคาถาปาฬิ',
                                                'si': 'ථෙරගාථාපාළි',
                                                'en': 'Theragāthāpāḷi',
                                                'hi': 'थेरगाथापाळि',
                                                'kh': 'ថេរគាថាបាឡិ',
                                                'lo': 'ເຖຣຄາຖາປາຬິ',
                                                'ln': 'ᨳᩮᩁᨣᩣᨳᩣᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/thera'}
                                        },
                                        {
                                            label: 'Therīgāthāpāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ထေရီဂါထာပါဠိ',
                                                'th': 'เถรีคาถาปาฬิ',
                                                'si': 'ථෙරීගාථාපාළි',
                                                'en': 'Therīgāthāpāḷi',
                                                'hi': 'थेरीगाथापाळि',
                                                'kh': 'ថេរីគាថាបាឡិ',
                                                'lo': 'ເຖຣີຄາຖາປາຬິ',
                                                'ln': 'ᨳᩮᩁᩦᨣᩣᨳᩣᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/theri'}
                                        },
                                        {
                                            label: 'Apadānapāḷi (pa)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'အပဒါနပါဠိ (ဒု)',
                                                'th': 'อปทานปาฬิ (ป)',
                                                'si': 'අපදානපාළි (ප)',
                                                'en': 'Apadānapāḷi (pa)',
                                                'hi': 'अपदानपाळि (प)',
                                                'kh': 'អបទានបាឡិ (ប)',
                                                'lo': 'ອປທານປາຬິ (ປ)',
                                                'ln': 'য়ᩮᨴᩣᨶᩣᩊᩥ (ᨸ)',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/ap1'}
                                        },
                                        {
                                            label: 'Apadānapāḷi (du)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'အပဒါနပါဠိ (ဒု)',
                                                'th': 'อปทานปาฬิ (ทุ)',
                                                'si': 'අපදානපාළි (දු)',
                                                'en': 'Apadānapāḷi (du)',
                                                'hi': 'अपदानपाळि (दु)',
                                                'kh': 'អបទានបាឡិ (ទុ)',
                                                'lo': 'ອປທານປາຬິ (ທຸ)',
                                                'ln': 'ᨭᩮᨴᩣᨶᨣᩊᩥ (ᨴᩩ)',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/ap2'}
                                        },
                                        {
                                            label: 'Buddhavaṃsapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဗုဒ္ဓဝံသပါဠိ',
                                                'th': 'พุทฺธวํสปาฬิ',
                                                'si': 'බුද්ධවංසපාළි',
                                                'en': 'Buddhavaṃsapāḷi',
                                                'hi': 'बुद्धवंसपाळि',
                                                'kh': 'ពុទ្ធវំសបាឡិ',
                                                'lo': 'ພຸທ຺ຘວໍສປາຬິ',
                                                'ln': 'ᨻᩩᨴ᩠ᨵᩅᩴᩈᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/bv'}
                                        },
                                        {
                                            label: 'Cariyāpiṭakapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'စရိယာပိဋကပါဠိ',
                                                'th': 'จริยาปิฏกปาฬิ',
                                                'si': 'චරියාපිටකපාළි',
                                                'en': 'Cariyāpiṭakapāḷi',
                                                'hi': 'चरियापिटकपाळि',
                                                'kh': 'ចរិយាបិដកបាឡិ',
                                                'lo': 'ຈຣິຍາປິຏກປາຬິ',
                                                'ln': 'ᨧᩁᩥᨿᩣᨸᩥᨭᨠᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/cariya'}
                                        },
                                        {
                                            label: 'Jātakapāḷi (pa)',
                                            collapsed: true, 
                                            translations: {
                                                'my': 'ဇာတကပါဠိ (ပ)',
                                                'th': 'ชาตกปาฬิ (ป)',
                                                'si': 'ජාතකපාළි (ප)',
                                                'en': 'Jātakapāḷi (pa)',
                                                'hi': 'जातकपाळि (प)',
                                                'kh': 'ជាតកបាឡិ (ប)',
                                                'lo': 'ຊາຕກປາຬິ (ປ)',
                                                'ln': 'ᨸᩮᨴᩣᨶᨣᩊᩥ (ᨸ)',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/ja1'}
                                        },
                                        {
                                            label: 'Jātakapāḷi (du)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ဇာတကပါဠိ (ဒု)',
                                                'th': 'ชาตกปาฬิ (ทุ)',
                                                'si': 'ජාතකපාළි (දු)',
                                                'en': 'Jātakapāḷi (du)',
                                                'hi': 'जातकपाळि (दु)',
                                                'kh': 'ជាតកបាឡិ (ទុ)',
                                                'lo': 'ຊາຕກປາຬິ (ທຸ)',
                                                'ln': 'ᨩᩣᨲᨠᨸᩣᩊᩥ (ᨲ)'
                                            },
                                            autogenerate: {directory: 'mula/su/ku/ja2'}
                                        },
                                        {
                                            label: 'Mahāniddesapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'မဟာနိဒ္ဒေသပါဠိ',
                                                'th': 'มหานิทฺเทสปาฬิ',
                                                'si': 'මහානිද්දෙසපාළි',
                                                'en': 'Mahāniddesapāḷi',
                                                'hi': 'महानिद्देसपाळि',
                                                'kh': 'មហានិទ្ទេសបាឡិ',
                                                'lo': 'ມຫານິທ຺ເທສປາຬິ',
                                                'ln': 'ᨾᩉᩣᨶᩥᨴ᩠ᨴᩮᩈᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/mahanid'}
                                        },
                                        {
                                            label: 'Cūḷaniddesapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'စူဠနိဒ္ဒေသပါဠိ',
                                                'th': 'จูฬนิทฺเทสปาฬิ',
                                                'si': 'චූළනිද්දෙසපාළි',
                                                'en': 'Cūḷaniddesapāḷi',
                                                'hi': 'चूळनिद्देसपाळि',
                                                'kh': 'ចូឡនិទ្ទេសបាឡិ',
                                                'lo': 'ຈູຬນິທ຺ເທສປາຬິ',
                                                'ln': 'ᨧᩪᩊᨶᩥᨴ᩠ᨴᩮᩈᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/culanid'}
                                        },
                                        {
                                            label: 'Paṭisambhidāmaggapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပဋိသမ္ဘိဒါမဂ္ဂပါဠိ',
                                                'th': 'ปฏิสมฺภิทามคฺคปาฬิ',
                                                'si': 'පටිසම්භිදාමග්ගපාළි',
                                                'en': 'Paṭisambhidāmaggapāḷi',
                                                'hi': 'पटिसम्भिदामग्गपाळि',
                                                'kh': 'បដិសម្ភិទាមគ្គបាឡិ',
                                                'lo': 'ປຏິສມ຺ຠິທາມຄ຺ຄປາຬິ',
                                                'ln': 'ᨸᨭᩥᩈᨾ᩠ᨽᩥᨴᩣᨾᨣ᩠ᨣᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/patis'}
                                        },
                                        {
                                            label: 'Milindapañhapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'မိလိန္ဒပဉှပါဠိ',
                                                'th': 'มิลินฺทปญฺหปาฬิ',
                                                'si': 'මිලින්දපඤ්හපාළි',
                                                'en': 'Milindapañhapāḷi',
                                                'hi': 'मिलिन्दपञ्हपाळि',
                                                'kh': 'មិលិន្ទបញ្ហបាឡិ',
                                                'lo': 'ມິລິນ຺ທປຎ຺ຫປາຬິ',
                                                'ln': 'ᨾᩥᩃᩥᨶ᩠ᨴᨸᨬ᩠ᩉᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/milin'}
                                        },
                                        {
                                            label: 'Nettippakaraṇapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'နေတ္တိပ္ပကရဏပါဠိ',
                                                'th': 'เนตฺติปฺปกรณปาฬิ',
                                                'si': 'නෙත්තිප්පකරණපාළි',
                                                'en': 'Nettippakaraṇapāḷi',
                                                'hi': 'नेत्तिप्पकरणपाळि',
                                                'kh': 'នេត្តិប្បករណបាឡិ',
                                                'lo': 'ເນຕ຺ຕິປ຺ປກຣຓປາຬິ',
                                                'ln': 'ᨶᩮᨲ᩠ᨲᩥᨸ᩠ᨸᨠᩁᨱᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/netti'}
                                        },
                                        {
                                            label: 'Peṭakopadesapāḷi', 
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပေဋကောပဒေသပါဠိ',
                                                'th': 'เปฏโกปเทสปาฬิ',
                                                'si': 'පෙටකොපදෙසපාළි',
                                                'en': 'Peṭakopadesapāḷi',
                                                'hi': 'पेटकोपदेसपाळि',
                                                'kh': 'បេដកោបទេសបាឡិ',
                                                'lo': 'ເປຏໂກປເທສປາຬິ',
                                                'ln': 'ᨸᩮᨭᨠᩮᩣᨸᨴᩮᩈᨸᩣᩊᩥ',
                                            },
                                            autogenerate: {directory: 'mula/su/ku/petako'}
                                        },                                        
                                    ]
                                }
                            ],
                        },
                        {
                            label: 'Abhidhammapiṭaka',
                            collapsed: true,
                            translations: { 
                                'my': 'အဘိဓမ္မပိဋက',
                                'th': 'อภิธมฺมปิฏก',
                                'si': 'අභිධම්මපිටක',
                                'en': 'Abhidhammapiṭaka',
                                'hi': 'अभिधम्मपिटक',
                                'kh': 'អភិធម្មបិដក',
                                'lo': 'ອຠິຘມ຺ມປິຏກ',
                                'ln': 'ᩋᨽᩥᨵᨾ᩠ᨾᨸᩥᨭᨠ',
                            },
                            items: [
                                {
                                    label: 'Dhammasaṅgaṇīpāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ဓမ္မသင်္ဂဏီပါဠိ',
                                        'th': 'ธมฺมสงฺคณีปาฬิ',
                                        'si': 'ධම්මසඞ්ගණීපාළි',
                                        'en': 'Dhammasaṅgaṇīpāḷi',
                                        'hi': 'धम्मसङ्गणीपाळि',
                                        'kh': 'ធម្មសង្គណីបាឡិ',
                                        'lo': 'ຘມ຺ມສງ຺ຄຓີປາຬິ',
                                        'ln': 'ᨵᨾ᩠ᨾᩈᨦ᩠ᨣᨱᩦᨸᩣᩊᩥ',
                                    },
                                    autogenerate: { directory: 'mula/bi/dhs' },
                                },
                                {
                                    label: 'Vibhaṅgapāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ဝိဘင်္ဂပါဠိ',
                                        'th': 'วิภงฺคปาฬิ',
                                        'si': 'විභඞ්ගපාළි',
                                        'en': 'Vibhaṅgapāḷi',
                                        'hi': 'विभङ्गपाळि',
                                        'kh': 'វិភង្គបាឡិ',
                                        'lo': 'ວິຠງ຺ຄປາຬິ',
                                        'ln': 'ᩅᩥᨽᨦ᩠ᨣᨸᩣᩊᩥ',
                                    },
                                    autogenerate: { directory: 'mula/bi/vibh' },
                                },
                                {
                                    label: 'Dhātukathāpāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ဓာတုကထာပါဠိ',
                                        'th': 'ธาตุกถาปาฬิ',
                                        'si': 'ධාතුකථාපාළි',
                                        'en': 'Dhātukathāpāḷi',
                                        'hi': 'धातुकथापाळि',
                                        'kh': 'ធាតុកថាបាឡិ',
                                        'lo': 'ຘາຕຸກຖາປາຬິ',
                                        'ln': 'ᨵᩣᨲᩩᨠᨳᩣᨸᩣᩊᩥ',
                                    },
                                    autogenerate: { directory: 'mula/bi/dhat' },
                                },
                                {
                                    label: 'Puggalapaññattipāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ပုဂ္ဂလပညတ္တိပါဠိ',
                                        'th': 'ปุคฺคลปญฺญตฺติปาฬิ',
                                        'si': 'පුග්ගලපඤ්ඤත්තිපාළි',
                                        'en': 'Puggalapaññattipāḷi',
                                        'hi': 'पुग्गलपञ्ञत्तिपाळि',
                                        'kh': 'បុគ្គលបញ្ញត្តិបាឡិ',
                                        'lo': 'ປຸຄ຺ຄລປຎ຺ຎຕ຺ຕິປາຬິ',
                                        'ln': 'ᨸᩩᨣ᩠ᨣᩃᨸᨬ᩠ᨬᨲ᩠ᨲᩥᨸᩣᩊᩥ',
                                    },
                                    autogenerate: { directory: 'mula/bi/pug' },
                                },
                                {
                                    label: 'Kathāvatthupāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ကထာဝတ္ထုပါဠိ',
                                        'th': 'กถาวตฺถุปาฬิ',
                                        'si': 'කථාවත්ථුපාළි',
                                        'en': 'Kathāvatthupāḷi',
                                        'hi': 'कथावत्थुपाळि',
                                        'kh': 'កថាវត្ថុបាឡិ',
                                        'lo': 'ກຖາວຕ຺ຖຸປາຬິ',
                                        'ln': 'ᨠᨳᩣᩅᨲ᩠ᨳᩩᨸᩣᩊᩥ',
                                    },
                                    autogenerate: { directory: 'mula/bi/kv' },
                                },
                                {
                                    label: 'Yamakapāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ယမကပါဠိ',
                                        'th': 'ยมกปาฬิ',
                                        'si': 'යමකපාළි ', 
                                        'en': 'Yamakapāḷi', 
                                        'hi': 'यमकपाळि', 
                                        'kh': 'យមកបាឡិ', 
                                        'lo': 'ຍມກປາຬິ', 
                                        'ln': 'ᨿᨾᨠᨸᩣᩊᩥ', 
                                    },
                                    items: [
                                        { 
                                            label: 'Yamakapāḷi (pa)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ယမကပါဠိ (ပ)',
                                                'th': 'ยมกปาฬิ (ป)',
                                                'si': 'යමකපාළි (ප)', 
                                                'en': 'Yamakapāḷi (pa)', 
                                                'hi': 'यमकपाळि (प)', 
                                                'kh': 'យមកបាឡិ (ប)', 
                                                'lo': 'ຍມກປາຬິ (ປ)', 
                                                'ln': 'ᨿᨾᨠᨸᩣᩊᩥ (ᨸ)', 
                                            },
                                            autogenerate: { directory: 'mula/bi/yam1' } 
                                        },                                            
                                        { 
                                            label: 'Yamakapāḷi (du)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ယမကပါဠိ (ဒု)',
                                                'th': 'ยมกปาฬิ (ทุ)',
                                                'si': 'යමකපාළි (දු)', 
                                                'en': 'Yamakapāḷi (du)', 
                                                'hi': 'यमकपाळि (दु)', 
                                                'kh': 'យមកបាឡិ (ទុ)', 
                                                'lo': 'ຍມກປາຬິ (ທຸ)', 
                                                'ln': 'ᨿᨾᨠᨸᩣᩊᩥ (ᨴᩩ)', 
                                            }, 
                                            autogenerate: { directory: 'mula/bi/yam2' }
                                        },                                           
                                        { 
                                            label: 'Yamakapāḷi (ta)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ယမကပါဠိ (တ)',
                                                'th': 'ยมกปาฬิ (ต)',
                                                'si': 'යමකපාළි (ත)', 
                                                'en': 'Yamakapāḷi (ta)', 
                                                'hi': 'यमकपाळि (त)', 
                                                'kh': 'យមកបាឡិ (ត)', 
                                                'lo': 'ຍມກປາຬິ (ຕ)', 
                                                'ln': 'ᨿᨾᨠᨸᩣᩊᩥ (ᨲ)', 
                                            },   
                                            autogenerate: { directory: 'mula/bi/yam3' }
                                        }                                         
                                    ],
                                },
                                {
                                    label: 'Paṭṭhānapāḷi',
                                    collapsed: true,
                                    translations: {
                                        'my': 'ပဋ္ဌာနပါဠိ',
                                        'th': 'ปฏฺฐานปาฬิ',
                                        'si': 'පට්ඨානපාළි',
                                        'en': 'Paṭṭhānapāḷi',
                                        'hi': 'पट्ठानपाळि',
                                        'kh': 'បដ្ឋានបាឡិ',
                                        'lo': 'ປຏ຺ຐານປາຬິ',
                                        'ln': 'ᨸᨭ᩠ᨮᩣᨶᨸᩣᩊᩥ',
                                    },
                                    items: [
                                        { 
                                            label: 'Paṭṭhānapāḷi (pa)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပဋ္ဌာနပါဠိ (ပ)',
                                                'th': 'ปฏฺฐานปาฬิ (ป)',
                                                'si': 'පට්ඨානපාළි (ප)',
                                                'en': 'Paṭṭhānapāḷi (pa)',
                                                'hi': 'पट्ठानपाळि (प)',
                                                'kh': 'បដ្ឋានបាឡិ (ប)',
                                                'lo': 'ປຏ຺ຐານປາຬິ (ປ)',
                                                'ln': 'ᨸᨭ᩠ᨮᩣᨶᨸᩣᩊᩥ (ᨸ)',
                                            },
                                            autogenerate: { directory: 'mula/bi/patth1' }
                                        },
                                        { 
                                            label: 'Paṭṭhānapāḷi (du)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပဋ္ဌာနပါဠိ (ဒု)',
                                                'th': 'ปฏฺฐานปาฬิ (ทุ)',
                                                'si': 'පට්ඨානපාළි (දු)',
                                                'en': 'Paṭṭhānapāḷi (du)',
                                                'hi': 'पट्ठानपाळि (दु)',
                                                'kh': 'បដ្ឋានបាឡិ (ទុ)',
                                                'lo': 'ປຏ຺ຐານປາຬິ (ທຸ)',
                                                'ln': 'ᨸᨭ᩠ᨮᩣᨶᨸᩣᩊᩥ (ᨴᩩ)',
                                            },
                                            autogenerate: { directory: 'mula/bi/patth2' }
                                        },
                                        { 
                                            label: 'Paṭṭhānapāḷi (ta)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပဋ္ဌာနပါဠိ (တ)',
                                                'th': 'ปฏฺฐานปาฬิ (ต)',
                                                'si': 'පට්ඨානපාළි (ත)',
                                                'en': 'Paṭṭhānapāḷi (ta)',
                                                'hi': 'पट्ठानपाळि (त)',
                                                'kh': 'បដ្ឋានបាឡិ (ត)',
                                                'lo': 'ປຏ຺ຐານປາຬິ (ຕ)',
                                                'ln': 'ᨸᨭ᩠ᨮᩣᨶᨸᩣᩊᩥ (ᨲ)',
                                            },
                                            autogenerate: { directory: 'mula/bi/patth3' }
                                        },
                                        { 
                                            label: 'Paṭṭhānapāḷi (ca)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပဋ္ဌာနပါဠိ (စ)',
                                                'th': 'ปฏฺฐานปาฬิ (จ)',
                                                'si': 'පට්ඨානපාළි (ච)',
                                                'en': 'Paṭṭhānapāḷi (ca)',
                                                'hi': 'पट्ठानपाळि (च)',
                                                'kh': 'បដ្ឋានបាឡិ (ច)',
                                                'lo': 'ປຏ຺ຐານປາຬິ (ຈ)',
                                                'ln': 'ᨸᨭ᩠ᨮᩣᨶᨸᩣᩊᩥ (ᨧ)',
                                            },
                                            autogenerate: { directory: 'mula/bi/patth4' }
                                        },
                                        { 
                                            label: 'Paṭṭhānapāḷi (pañca)',
                                            collapsed: true,
                                            translations: {
                                                'my': 'ပဋ္ဌာနပါဠိ (ပဉ္စ)',
                                                'th': 'ปฏฺฐานปาฬิ (ปญฺจ)',
                                                'si': 'පට්ඨානපාළි (පඤ්ච)',
                                                'en': 'Paṭṭhānapāḷi (pañca)',
                                                'hi': 'पट्ठानपाळि (पञ्च)',
                                                'kh': 'បដ្ឋានបាឡិ (បញ្ច)',
                                                'lo': 'ປຏ຺ຐານປາຬິ (ປຎ຺ຈ)',
                                                'ln': 'ᨸᨭ᩠ᨮᩣᨶᨸᩣᩊᩥ (ᨸᨬ᩠ᨧ)',
                                            },
                                            autogenerate: { directory: 'mula/bi/patth5' }
                                        },
                                    ]
                                },
                            ]
                        },
                    ],
                  },
			],
		}),
	],
});
